version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: planner
      POSTGRES_PASSWORD: plannerpw
      POSTGRES_DB: plannerdb
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://planner:plannerpw@db:5432/plannerdb
      JWT_SECRET: change-me
    ports:
      - "3001:3001"
volumes:
  pgdata:
